name: Ruby Setup Test

on:
  workflow_dispatch:

jobs:
  setup-ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.2"
          bundler-cache: true
      - run: ruby -v
